### ISSUE TITLE
Cursor not moving back to the correct place on insert mode backwards correction

### ISSUE THREAD

**Issue by arecarn** [arecarn/spell-utils.vim#2]
When correcting the following string where the cursor is `[ ]` using insert mode backwards correction
`This way ytou do[ ]`

The cursor moved back to the wrong position 
`This way ytou d[o]`

**Comment by DarwinSenior** [comment]
Hi, I was originally used to thinking about using this plugin, but I found this
https://stackoverflow.com/questions/5312235/how-do-i-correct-vim-spelling-mistakes-quicker
which might be a much neater solution.

**Comment by arecarn** [comment]
Thanks for your consideration :)

I don't think the use of \`] in right in the answer you linked to, since :help states that \`] jumps to the last character of the previously changed or yanked text.

Although this plugins solution isn't the neatest for insert mode corrections it does try to go to the last insert mode location while also taking into account for changes in the line length due to spelling corrections, which the solution you link to does not.

**Comment by arecarn** [comment]
Related to this issue I can't seem to reproduce the issue in Vim or Neovim
